;;; Automatically generated by ‘recentf’ on Thu Nov 13 10:46:51 2025.

(setq recentf-list
      '(
        "~/Documents/Obsidian/obsidian/Universidad/4º año/Primer Semestre/Estructura de datos avanzada/Tema 5 Grafos/Ejercicios/New/Ejercicio2/src/main/java/es/urjc/grafo/EDA/graph/EMDigraph.java"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
